service: app-dockerfile-${opt:stage, 'development'}

configValidationMode: error

custom:
  prune:
    automatic: true
    number: 1

provider:
  name: aws
  logRetentionInDays: 7
  # runtime: nodejs20.x
  stage: ${opt:stage, 'development'}
  region: us-east-1
  timeout: 15
  apiGateway:
    shouldStartNameWithService: true
  memorySize: 128

package:
  individually: true
  excludeDevDependencies: false
  patterns:
    - "dist/**"
    - "!node_modules/**"

functions:
  handler:
    handler: apps/api/src/handler.handler
    events:
      - httpApi:
          path: /{proxy+}
          method: any

plugins:
  - serverless-plugin-common-excludes
  - serverless-offline
